/* Hackera — данни за статичния сайт (двуезичен: bg/en) */
const CATS = [
  { id: "web", icon: "globe", name: { bg: "Разработка на сайтове", en: "Web Development" }, items: [
    ["Изработка на фирмен сайт", "Съвременен сайт с всички основни страници, готов да представя бизнеса ви в интернет.", "Business Website Development", "A modern site with all core pages, ready to represent your business online."],
    ["Целеви страници", "Отделна страница, насочена към едно предложение или кампания, за най-много запитвания и продажби.", "Landing Pages", "A dedicated page focused on one offer or campaign, built for maximum conversion."],
    ["Онлайн магазини", "Пълноценен магазин с каталог, количка и плащане за продажби в интернет.", "Online Stores (E-commerce)", "A full store with catalog, cart and checkout for selling online."],
    ["Разработка на WordPress сайтове", "Изграждане на сайт върху WordPress — гъвкав и лесен за самостоятелна поддръжка.", "WordPress Development", "Building a site on WordPress — flexible and easy to maintain yourself."],
    ["Разработка на Shopify магазини", "Онлайн магазин върху Shopify, готов за бързо начало на продажбите.", "Shopify Development", "An online store on Shopify, ready to start selling fast."],
    ["Уеб приложения по поръчка", "Уеб приложение, изградено по мярка за конкретен работен процес във фирмата.", "Custom Web Apps", "A web application built to fit a specific business process."],
    ["Уеб дизайн и удобство на ползване", "Визуален дизайн на интерфейса, съобразен с начина, по който хората наистина го ползват.", "Web Design (UI/UX)", "Interface design built around how people actually use it."],
    ["Адаптиране за мобилни устройства", "Преработване на съществуващ сайт, за да изглежда добре на всяко устройство.", "Responsive/Mobile Adaptation", "Adapting an existing site to look great on every device."],
    ["Поддръжка на сайтове", "Редовни технически грижи, за да работи сайтът ви гладко и сигурно.", "Website Maintenance", "Ongoing technical care so your site runs smoothly and safely."],
    ["Преместване на сайтове", "Прехвърляне на сайт към нов хостинг или нова платформа без прекъсване.", "Website Migration", "Moving a site to new hosting or a new platform without downtime."],
    ["Ускоряване на сайтове", "По-бързо зареждане на сайта за по-приятно изживяване и по-добро класиране в търсачките.", "Speed Optimization", "Faster load times for a better experience and better SEO."],
    ["Свързване с външни системи (API)", "Свързване на сайта с външни системи и услуги чрез програмни интерфейси.", "API Integrations", "Connecting your site to external systems and services."],
    ["Разработка на добавки", "Изработка на разширение по поръчка за конкретна функция на сайта.", "Plugin Development", "A custom plugin built for a specific site feature."],
    ["Теми за WordPress", "Дизайн на тема по поръчка за WordPress сайт.", "WordPress Themes", "Custom WordPress theme design."],
    ["Прогресивни уеб приложения", "Сайт, който се държи като приложение — работи без интернет и може да се инсталира.", "Progressive Web Apps (PWA)", "A site that behaves like an app — works offline and installs."],
    ["Сравнително тестване на целеви страници", "Изпитване на различни варианти на страница, за да откриете кой води до повече продажби.", "Landing Page A/B Testing", "Testing page versions to find out which one converts better."],
    ["Чат асистент за сайт", "Автоматизиран чат, който отговаря на клиентите директно на сайта.", "Website Chatbots", "An automated chat that answers customers right on your site."],
    ["Онлайн система за резервации", "Календар за резервации, през който клиентите сами си запазват час.", "Online Booking Systems", "A booking calendar customers use to schedule themselves."],
    ["Платформи с абонамент", "Система за платено съдържание или услуги срещу месечна такса.", "Subscription Platforms", "A system for paid content or services on subscription."],
    ["Сайтове с платено членство", "Затворена зона за регистрирани потребители с изключително съдържание.", "Membership Sites", "A gated area for registered users with exclusive content."],
  ]},
  { id: "seo", icon: "trending-up", name: { bg: "SEO услуги", en: "SEO Services" }, items: [
    ["Одит за SEO", "Пълен преглед на сайта, за да откриете какво пречи на класирането му.", "SEO Audit", "A full review of the site to find what's holding back its ranking."],
    ["Оптимизация на самите страници", "Подобряване на съдържанието и структурата на страниците за търсачките.", "On-page SEO", "Optimizing content and structure of pages for search engines."],
    ["Изграждане на външни връзки", "Получаване на препратки от други сайтове, за да расте авторитетът ви.", "Off-page SEO (Link Building)", "Building links from other sites to grow your authority."],
    ["Техническо SEO", "Отстраняване на технически проблеми, които пречат на Google да индексира сайта.", "Technical SEO", "Fixing technical issues that block Google from indexing you."],
    ["Местно SEO (Google Business Profile)", "Оптимизация за търсене по местоположение, за да ви намират клиенти във вашия град.", "Local SEO (Google Business Profile)", "Optimizing for local search so nearby customers find you."],
    ["Проучване на ключови думи", "Откриване на точните думи, които клиентите ви търсят в Google.", "Keyword Research", "Finding the exact words your customers search for."],
    ["Анализ на конкурентите", "Преглед на стратегиите на конкурентите, за да откриете възможности за вас.", "Competitor Analysis", "Reviewing competitor strategies to find opportunities for you."],
    ["Текстове за SEO", "Текстове, писани едновременно за читателя и за търсачките.", "SEO Copywriting", "Content written for readers and search engines at once."],
    ["Маркиране на структурирани данни", "Код, който помага на Google да разбира по-добре съдържанието на страницата.", "Schema Markup (Structured Data)", "Code that helps Google better understand your page content."],
    ["SEO за мобилни устройства", "Оптимизация специално за представянето на сайта при търсене от телефон.", "Mobile SEO", "Optimization focused on mobile search performance."],
    ["Оптимизация за гласово търсене", "Приспособяване на съдържанието за въпроси, зададени гласово към асистенти.", "Voice Search Optimization", "Adapting content for questions asked to voice assistants."],
    ["SEO за онлайн магазини", "SEO стратегия специално за продуктови страници и категории в онлайн магазин.", "E-commerce SEO", "SEO strategy specifically for product and category pages."],
    ["Международно SEO", "Настройка на сайта за класиране в няколко държави и на няколко езика едновременно.", "International SEO", "Setting up a site to rank across multiple countries and languages."],
    ["Проследяване и отчети за SEO", "Редовно следене на позициите и посещенията с ясни отчети.", "SEO Monitoring & Reports", "Ongoing tracking of rankings and traffic with clear reports."],
    ["Анализ на липсващо съдържание", "Откриване на теми, които конкурентите покриват, а вие — все още не.", "Content Gap Analysis", "Finding topics competitors cover that you don't yet."],
  ]},
  { id: "marketing", icon: "megaphone", name: { bg: "Дигитален маркетинг", en: "Digital Marketing" }, items: [
    ["Платени реклами в Google (Google Ads)", "Платени реклами в Google, които се показват точно когато търсят вашата услуга.", "PPC Ads (Google Ads)", "Paid ads that appear exactly when people search for your service."],
    ["Реклами във Facebook и Instagram", "Насочени реклами към точната аудитория в платформите на Meta.", "Facebook/Instagram Ads", "Targeted ads reaching the right audience on Meta platforms."],
    ["Реклами в TikTok", "Кратки видео реклами, достигащи до по-млада аудитория в TikTok.", "TikTok Ads", "Short video ads reaching a younger audience on TikTok."],
    ["Реклами в LinkedIn", "Реклами, насочени към професионалисти и фирмена аудитория в LinkedIn.", "LinkedIn Ads", "Ads targeting professionals and B2B audiences on LinkedIn."],
    ["Реклами в YouTube", "Видео реклами преди или по време на съдържание в YouTube.", "YouTube Ads", "Video ads shown before or during YouTube content."],
    ["Кампании за повторно достигане", "Реклами към хора, посетили сайта ви, но не завършили покупка.", "Retargeting Campaigns", "Ads aimed at people who visited but didn't convert."],
    ["Банерни реклами", "Рекламни банери, показвани в мрежа от партньорски сайтове.", "Display Ads", "Banner ads shown across a network of partner sites."],
    ["Автоматизирано рекламиране", "Автоматично купуване на рекламно място в реално време.", "Programmatic Advertising", "Automated buying of ad space in real time."],
    ["Партньорски маркетинг", "Партньорска програма, в която други продават вместо вас срещу комисиона.", "Affiliate Marketing", "A partner program where third parties sell for a commission."],
    ["Маркетинг с влиятелни личности", "Партньорства с популярни личности, които представят продукта пред своята аудитория.", "Influencer Marketing", "Partnering with influencers to reach their audience."],
    ["Маркетинг по имейл", "Кампании по имейл за задържане и активиране на клиенти.", "Email Marketing", "Campaigns for retaining and re-engaging customers."],
    ["Маркетинг със съобщения", "Кратки текстови съобщения за промоции и напомняния към клиенти.", "SMS Marketing", "Short text messages for promotions and reminders."],
    ["Маркетинг кампании през WhatsApp", "Пряка връзка с клиентите през WhatsApp за оферти и помощ.", "WhatsApp Marketing", "Direct customer communication via WhatsApp for offers and support."],
    ["Автоматизиран маркетинг", "Автоматични поредици от съобщения, задействани от поведението на клиента.", "Marketing Automation", "Automated message sequences triggered by customer behavior."],
    ["Привличане на потенциални клиенти", "Кампании, насочени специално към набиране на нови потенциални клиенти.", "Lead Generation", "Campaigns focused specifically on gathering new leads."],
    ["Повишаване на продажбите от сайта", "Подобряване на сайта, за да превръща повече посетители в клиенти.", "Conversion Rate Optimization (CRO)", "Improving the site to turn more visitors into customers."],
    ["Бърз растеж чрез експерименти", "Бързи и евтини опити за откриване на канали за растеж.", "Growth Hacking", "Fast, low-cost experiments to find growth channels."],
    ["Маркетингова стратегия", "Цялостен план как да достигнете и убедите аудиторията си.", "Marketing Strategy", "A full plan for reaching and convincing your audience."],
    ["Маркетингов одит", "Преглед на текущите маркетингови усилия и къде се губят пари и резултати.", "Marketing Audit", "A review of current marketing efforts and where results are lost."],
    ["Стратегии за повторно привличане", "План за връщане на посетители, които вече са проявили интерес.", "Remarketing Strategies", "A strategy for bringing back visitors who showed interest."],
  ]},
  { id: "social", icon: "share-2", name: { bg: "Социални мрежи", en: "Social Media" }, items: [
    ["Управление на социални мрежи", "Ежедневно управление на профилите ви в социалните мрежи.", "Social Media Management (SMM)", "Day-to-day management of your social media profiles."],
    ["Създаване на съдържание за социални мрежи", "Планиране и изработка на публикации, съобразени с всяка платформа.", "Social Media Content Creation", "Planning and creating posts tailored to each platform."],
    ["Кратки видеа за Instagram", "Кратки вертикални видеа, направени да се представят добре в Instagram.", "Instagram Reels Production", "Short vertical videos built to perform well on Instagram."],
    ["Видеа за TikTok", "Видео съдържание, заснето и монтирано специално за TikTok.", "TikTok Video Production", "Video content shot and edited specifically for TikTok."],
    ["Управление на Facebook страница", "Поддръжка и развитие на фирмената ви страница във Facebook.", "Facebook Page Management", "Ongoing management and growth of your Facebook business page."],
    ["Управление на фирмен профил в LinkedIn", "Водене на фирмения профил и присъствие в LinkedIn.", "LinkedIn Company Page Management", "Managing your company profile and presence on LinkedIn."],
    ["Стратегия за социални мрежи", "План какво, кога и защо публикувате в социалните мрежи.", "Social Media Strategy", "A plan for what, when and why you post on social media."],
    ["Управление на общност", "Активно общуване и изграждане на общност около марката ви.", "Community Management", "Active engagement and community-building around your brand."],
    ["Наблюдение на коментари", "Следене и отговаряне на коментари под публикациите ви.", "Comment Moderation", "Monitoring and responding to comments on your posts."],
    ["Следене на споменавания", "Проследяване какво се говори за марката ви в интернет.", "Social Listening", "Tracking what's being said about your brand online."],
    ["Стратегия за хаштагове", "Проучване и подбор на хаштагове за по-голяма видимост.", "Hashtag Strategy", "Research and selection of hashtags for greater reach."],
    ["Одит на социални мрежи", "Преглед на профилите ви и препоръки за подобрение.", "Social Media Audit", "A review of your profiles with improvement recommendations."],
    ["Търсене на влиятелни личности", "Намиране и договаряне с подходящи популярни личности за вашата марка.", "Influencer Outreach", "Finding and negotiating with the right influencers for your brand."],
    ["Кампании със съдържание от клиенти", "Кампании, които насърчават клиентите сами да създават съдържание за марката.", "UGC Campaigns", "Campaigns that encourage customers to create content for your brand."],
    ["Управление на кризи в социалните мрежи", "Бърза и премерена реакция при негативна вълна в социалните мрежи.", "Social Media Crisis Management", "A fast, measured response to a negative wave online."],
  ]},
  { id: "content", icon: "pen-tool", name: { bg: "Съдържание и копирайтинг", en: "Content & Copywriting" }, items: [
    ["Текстове за сайтове", "Текстове за всяка страница на сайта, писани да убеждават и информират.", "Website Copywriting", "Page-by-page copy written to persuade and inform."],
    ["Статии за блог", "Редовни статии, които привличат посетители и изграждат авторитет.", "Blog Articles", "Regular articles that drive traffic and build authority."],
    ["Текстове за SEO", "Съдържание, съобразено с конкретните търсения на клиентите ви.", "SEO Content", "Content optimized around your customers' actual searches."],
    ["Описания на продукти", "Кратки описания, които продават, за всеки продукт в магазина ви.", "Product Descriptions", "Short, persuasive copy for every product in your store."],
    ["Текстове за имейли", "Текстове за имейл кампании, писани така, че да бъдат отворени и да водят до действие.", "Email Copy", "Email campaign copy written to be opened and acted on."],
    ["Сценарии за реклами", "Кратки и въздействащи текстове за видео и звукови реклами.", "Ad Scripts", "Short, punchy scripts for video and audio ads."],
    ["Техническо писане", "Ясни ръководства и документация за продукт или услуга.", "Technical Writing", "Clear guides and documentation for a product or service."],
    ["Разказ за марката", "Създаване на история около марката, която остава в паметта.", "Brand Storytelling", "Building a brand narrative that sticks in memory."],
    ["Текстове за социални мрежи", "Текстове, съобразени с тона и формата на всяка платформа.", "Social Media Copy", "Copy tailored to the tone and format of each platform."],
    ["Писане на аналитични документи", "Задълбочен документ, показващ опит и знания по конкретна тема.", "Whitepaper Writing", "An in-depth document showcasing expertise on a topic."],
    ["Описание на успешни проекти", "Разказ за конкретен успешен проект с измерими резултати.", "Case Study Writing", "A write-up of a successful project with measurable results."],
    ["Съобщения за медиите", "Официално съобщение за медиите при важна новина в бизнеса.", "Press Release Writing", "An official media statement for important business news."],
    ["Съдържание за бюлетини", "Редовен бюлетин, който държи клиентите ви информирани и ангажирани.", "Newsletter Content", "A regular newsletter that keeps customers informed and engaged."],
    ["Писане от името на друг", "Писане на съдържание от името на друг автор или марка.", "Ghostwriting", "Writing content under another author's or brand's name."],
    ["Преписване на звук и видео", "Превръщане на говорено съдържание в писмен текст.", "Audio/Video Transcription", "Turning spoken content into written text."],
  ]},
  { id: "design", icon: "palette", name: { bg: "Дизайн и графика", en: "Design & Graphics" }, items: [
    ["Дизайн на лого", "Ясен и запомнящ се знак, който представя марката ви визуално.", "Logo Design", "A clear, memorable mark that represents your brand visually."],
    ["Пакети за изграждане на марка", "Цялостен визуален пакет — цветове, шрифтове и стил на марката.", "Branding Packages", "A full visual package — colors, fonts and brand style."],
    ["Визуална идентичност", "Единен облик във всички материали на бизнеса ви.", "Visual Identity", "A consistent look across all of your business materials."],
    ["Дизайн на визитки", "Професионални визитки, съобразени с визуалния стил на марката.", "Business Card Design", "Professional cards matching your brand's visual style."],
    ["Брошури и листовки", "Печатни материали за представяне на бизнеса или на конкретна оферта.", "Brochures & Flyers", "Print materials to present your business or an offer."],
    ["Дизайн на банери", "Рекламни банери за сайтове и социални мрежи.", "Banner Design", "Ad banners for websites and social media."],
    ["Графики за социални мрежи", "Готови визуални шаблони за публикации в социалните мрежи.", "Social Media Graphics", "Ready-made visual templates for social media posts."],
    ["Дизайн на презентации", "Професионална презентация за клиенти, инвеститори или партньори.", "Presentation Design", "A professional deck for clients, investors or partners."],
    ["Инфографики", "Представяне на данни и информация във вид, който се възприема лесно.", "Infographics", "Turning data and information into an easy-to-read visual."],
    ["Илюстрации", "Оригинални илюстрации по поръчка за сайт, продукт или кампания.", "Illustration Services", "Original custom illustrations for a site, product or campaign."],
    ["Дизайн на опаковки", "Дизайн на опаковка, който се откроява на щанда.", "Packaging Design", "Package design that stands out on the shelf."],
    ["Дизайн на интерфейс за приложения", "Визуален дизайн на екраните в мобилно или уеб приложение.", "App UI Design", "Visual design of the screens in a mobile or web app."],
    ["Проучване на потребителите и скици на структурата", "Проучване на поведението на потребителите и скициране на структурата преди дизайна.", "UX Research & Wireframing", "Researching user behavior and sketching structure before design."],
    ["Дизайн на икони", "Комплект икони по поръчка, съобразени със стила на марката.", "Icon Design", "A custom icon set matching your brand's style."],
    ["Дизайн на шаблони за имейли", "Дизайн на шаблон за имейл кампании, готов за многократна употреба.", "Email Template Design", "A reusable template design for email campaigns."],
  ]},
  { id: "video", icon: "video", name: { bg: "Видео и звукова продукция", en: "Video & Audio Production" }, items: [
    ["Рекламни видеа", "Кратко видео, което представя продукт или услуга по привлекателен начин.", "Promo Videos", "A short video presenting a product or service attractively."],
    ["Анимирани видеа", "Анимирано видео за обясняване на идея или продукт.", "Animated Videos", "An animated video explaining an idea or product."],
    ["Обясняващи видеа", "Кратко видео, което обяснява как работи продукт или услуга.", "Explainer Videos", "A short video explaining how a product or service works."],
    ["Видео монтаж", "Професионален монтаж на заснет видео материал.", "Video Editing", "Professional editing of raw video footage."],
    ["Анимирана графика", "Анимирани графични елементи за видео и реклами.", "Motion Graphics", "Animated graphic elements for video and ads."],
    ["Продукция на подкасти", "Запис, монтаж и публикуване на епизоди на подкаст.", "Podcast Production", "Recording, editing and publishing podcast episodes."],
    ["Озвучаване с глас", "Професионално озвучаване или разказ за видео и реклами.", "Voiceover Recording", "Professional voiceover or narration for video and ads."],
    ["Музика за реклами", "Оригинална или подбрана музика за видео и звукови реклами.", "Music Production for Ads", "Original or licensed music for video and audio ads."],
    ["Предаване на живо", "Организация и техническа поддръжка на предаване на живо в интернет.", "Live Streaming Services", "Organization and technical support for live broadcasts."],
    ["Онлайн семинари", "Организиране и провеждане на семинар в интернет за вашата аудитория.", "Webinar Production", "Organizing and running an online seminar for your audience."],
    ["Видеа за социални мрежи", "Кратки видеа, оформени специално за социалните платформи.", "Social Media Video", "Short videos formatted specifically for social platforms."],
    ["Фирмени видеа", "Фирмено видео, представящо екипа, ценностите и дейността.", "Corporate Videos", "A company video showcasing team, values and work."],
    ["Видеа с демонстрация на продукт", "Видео, показващо продукта в реална употреба.", "Product Demo Videos", "A video showing the product in real use."],
    ["Видео на 360 градуса", "Панорамно видео, което позволява на зрителя да разглежда сцената свободно.", "360° Video", "Panoramic video letting the viewer explore the scene freely."],
    ["Заснемане с дрон", "Въздушни кадри, заснети с дрон за уникална гледна точка.", "Drone Videography", "Aerial footage shot with a drone for a unique angle."],
  ]},
  { id: "photo", icon: "camera", name: { bg: "Фотография", en: "Photography" }, items: [
    ["Фотография на продукти", "Професионални снимки на продукти за сайт и социални мрежи.", "Product Photography", "Professional product photos for your site and social media."],
    ["Фирмена фотография", "Фирмени снимки на екип, офис и събития.", "Corporate Photography", "Business photos of your team, office and events."],
    ["Фотография на събития", "Заснемане на фирмени събития, конференции и тържества.", "Event Photography", "Coverage of business events, conferences and parties."],
    ["Фотография на храна", "Апетитни снимки на храна за менюта и социални мрежи.", "Food Photography", "Appetizing food photos for menus and social media."],
    ["Фотография на недвижими имоти", "Професионални снимки на имоти за обяви и реклама.", "Real Estate Photography", "Professional property photos for listings and ads."],
    ["Портретна фотография", "Професионален портрет за екипа, сайта или LinkedIn.", "Headshot Photography", "A professional portrait for your team, site or LinkedIn."],
    ["Снимки за многократна употреба", "Изработка на оригинални снимки за многократна употреба в материали.", "Stock Photography Services", "Original photos produced for repeated use in materials."],
    ["Сватбена фотография", "Пълно заснемане на сватбено тържество от началото до края.", "Wedding Photography", "Full coverage of a wedding from start to finish."],
    ["Фотография за меню на ресторант", "Снимки на ястия, направени специално за печатно или дигитално меню.", "Restaurant Menu Photography", "Dish photos built specifically for a print or digital menu."],
    ["Въздушна фотография с дрон", "Въздушни снимки на имоти, събития или места.", "Aerial/Drone Photography", "Aerial photos of properties, events or locations."],
  ]},
  { id: "mobile", icon: "smartphone", name: { bg: "Мобилни приложения", en: "Mobile Apps" }, items: [
    ["Приложения за iOS", "Мобилно приложение, изградено специално за iPhone и iPad.", "iOS Development", "A mobile app built specifically for iPhone and iPad."],
    ["Приложения за Android", "Мобилно приложение, изградено специално за устройства с Android.", "Android Development", "A mobile app built specifically for Android devices."],
    ["Приложения за всички платформи (React Native/Flutter)", "Едно приложение, което работи едновременно на iOS и Android.", "Cross-platform (React Native/Flutter)", "One app that runs on both iOS and Android."],
    ["Оптимизация за магазините за приложения", "Подобряване на страницата на приложението за повече изтегляния.", "App Store Optimization (ASO)", "Optimizing your app store listing for more downloads."],
    ["Дизайн на мобилни приложения", "Визуален дизайн на екраните и последователността в приложението.", "Mobile App Design", "Visual design of the screens and flow in your app."],
    ["Поддръжка и обновяване на приложения", "Редовни обновявания и техническа поддръжка на приложението.", "App Maintenance & Updates", "Ongoing updates and technical support for your app."],
    ["Системи за известия", "Настройка на известия, които връщат потребителите в приложението.", "Push Notification Systems", "Setting up notifications that bring users back to the app."],
    ["Приложения за носими устройства", "Приложения за умни часовници и други носими устройства.", "Wearable Apps", "Apps for smartwatches and other wearable devices."],
    ["Вграждане на покупки в приложението", "Вграждане на плащания и абонаменти вътре в приложението.", "In-app Purchases Integration", "Building payments and subscriptions right into the app."],
    ["Вграждане на анализ в приложението", "Проследяване на поведението на потребителите вътре в приложението.", "App Analytics Integration", "Tracking user behavior inside the app."],
  ]},
  { id: "ecommerce", icon: "shopping-cart", name: { bg: "Електронна търговия", en: "E-commerce" }, items: [
    ["Настройка на онлайн магазин", "Пълна настройка на онлайн магазин, готов за първите продажби.", "Online Store Setup", "A full online store setup, ready for its first sales."],
    ["Управление на продуктовия каталог", "Подреждане и поддръжка на продуктите в магазина.", "Product Catalog Management", "Organizing and maintaining the products in your store."],
    ["Свързване със системи за плащане", "Свързване на магазина със системи за плащане в интернет.", "Payment Gateway Integration", "Connecting your store to online payment systems."],
    ["Системи за управление на наличностите", "Система за проследяване на наличностите в реално време.", "Inventory Management Systems", "A system for tracking stock levels in real time."],
    ["Подобряване на количката за пазаруване", "Подобряване на количката, за да се завършват повече поръчки.", "Shopping Cart Optimization", "Improving the cart to complete more orders."],
    ["Публикуване в големи платформи (Amazon, eBay)", "Публикуване и управление на продукти в големи онлайн платформи.", "Marketplace Listing (Amazon, eBay)", "Publishing and managing products on major online platforms."],
    ["Консултации за продажба без склад", "Съвети и настройка за модел на продажба без собствен склад.", "Dropshipping Consulting", "Advice and setup for a no-inventory sales model."],
    ["Фотография за онлайн магазини", "Снимки на продукти, подготвени за онлайн магазин.", "E-commerce Photography", "Product photos optimized for an online store."],
    ["Подобряване на поръчването", "Опростяване на процеса на плащане за по-малко изоставени колички.", "Checkout Optimization", "Simplifying checkout for fewer abandoned carts."],
    ["Кампании за изоставени колички", "Автоматични напомняния към клиенти, изоставили количката си.", "Abandoned Cart Campaigns", "Automatic reminders to customers who left their cart."],
    ["Настройка за няколко валути", "Настройка на магазина за продажби в няколко валути.", "Multi-currency Setup", "Setting up your store to sell in multiple currencies."],
    ["Платформи за продажба с абонамент", "Система за продажба на продукти или услуги срещу абонамент.", "Subscription Commerce Platforms", "A system for selling products or services on subscription."],
  ]},
  { id: "cloud", icon: "cloud", name: { bg: "Информационни технологии и облак", en: "IT & Cloud Services" }, items: [
    ["Облачен хостинг (AWS, Azure, Google Cloud)", "Хостинг на инфраструктура в облака, съобразен с нуждите на бизнеса.", "Cloud Hosting (AWS, Azure, Google Cloud)", "Cloud infrastructure hosting tailored to your business needs."],
    ["Администриране на сървъри", "Управление и поддръжка на сървърите, на които работи сайтът ви.", "Server Administration", "Managing and maintaining the servers your site runs on."],
    ["Регистрация на домейн", "Регистрация и управление на домейн името на бизнеса ви.", "Domain Registration", "Registering and managing your business's domain name."],
    ["Имейл хостинг", "Професионални имейл адреси на собствения ви домейн.", "Email Hosting", "Professional email addresses on your own domain."],
    ["Решения за резервни копия", "Автоматични резервни копия на данните ви за спокойствие.", "Backup Solutions", "Automatic backups of your data for peace of mind."],
    ["Защитена връзка (VPN)", "Сигурна отдалечена връзка към фирмената мрежа.", "VPN Services", "A secure remote connection to your company network."],
    ["Услуги за разработка и поддръжка (DevOps)", "Автоматизация на процесите по разработка и пускане на софтуер.", "DevOps Services", "Automating your development and release processes."],
    ["Автоматично тестване и пускане на версии", "Автоматизирано тестване и пускане на нови версии на софтуера.", "CI/CD Setup", "Automated testing and release of new software versions."],
    ["Управление на бази данни", "Управление, оптимизация и сигурност на базите данни.", "Database Management", "Managing, optimizing and securing your databases."],
    ["Консултации по информационни технологии", "Съвети за технологичните решения, най-подходящи за бизнеса ви.", "IT Consulting", "Advice on the technology choices that fit your business."],
    ["Преминаване към облака", "Прехвърляне на съществуваща инфраструктура в облачна среда.", "Cloud Migration", "Moving existing infrastructure into a cloud environment."],
    ["Архитектура без управление на сървъри", "Изграждане на приложения без нужда от управление на сървъри.", "Serverless Architecture", "Building applications without managing servers."],
  ]},
  { id: "security", icon: "shield-check", name: { bg: "Киберсигурност", en: "Cybersecurity" }, items: [
    ["Одит на сигурността", "Цялостна проверка на системите ви за слабости.", "Security Audit", "A full review of your systems for vulnerabilities."],
    ["Изпитване чрез проникване", "Контролирана симулация на атака, за да откриете слабите места.", "Penetration Testing", "A controlled simulated attack to find weak spots."],
    ["Настройка на защитна стена", "Защита на мрежата ви от нежелан достъп.", "Firewall Setup", "Protecting your network from unwanted access."],
    ["Сертификати за сигурна връзка (SSL)", "Шифрована връзка между сайта и посетителите му.", "SSL Certificates", "An encrypted connection between your site and its visitors."],
    ["Премахване на зловреден код", "Откриване и премахване на зловреден код от сайт или система.", "Malware Removal", "Finding and removing malicious code from a site or system."],
    ["Системи за управление на пароли", "Сигурно съхранение и управление на пароли в организацията.", "Password Management Systems", "Secure storage and management of passwords in your org."],
    ["Настройка на двустепенно удостоверяване", "Допълнителен слой сигурност при вход в системите ви.", "Two-factor Authentication Setup", "An extra layer of security when logging into your systems."],
    ["Реакция при инциденти", "Бърза реакция и възстановяване след инцидент със сигурността.", "Incident Response", "Fast reaction and recovery after a security incident."],
    ["Защита от претоварващи атаки (DDoS)", "Защита срещу атаки, които претоварват сайта ви.", "DDoS Protection", "Protection against overload attacks targeting your site."],
    ["Одит на мрежовата сигурност", "Преглед на цялата мрежова инфраструктура за рискове.", "Network Security Audit", "A review of your entire network infrastructure for risk."],
    ["Защита от вируси за откуп", "Мерки срещу зловреден софтуер, който шифрова данните ви и иска откуп.", "Ransomware Protection", "Measures against malware that encrypts your data for ransom."],
    ["Организиране на награди за открити слабости", "Организиране на програма, която възнаграждава откриването на слабости.", "Bug Bounty Program Coordination", "Organizing a program that rewards finding vulnerabilities."],
  ]},
  { id: "data", icon: "bar-chart-3", name: { bg: "Данни и анализи", en: "Data & Analytics" }, items: [
    ["Настройка на Google Analytics", "Настройка на проследяване на посещенията и поведението на сайта ви.", "Google Analytics Setup", "Setting up tracking for your site's traffic and behavior."],
    ["Визуализация на данни", "Превръщане на суровите данни в ясни визуални отчети.", "Data Visualization", "Turning raw data into clear visual reports."],
    ["Бизнес анализи", "Системи за анализ на данни в помощ на бизнес решенията.", "Business Intelligence", "Data analysis systems supporting business decisions."],
    ["Анализ на данни и отчети", "Редовни отчети, които показват какво работи и какво не.", "Data Analysis & Reports", "Regular reports showing what's working and what isn't."],
    ["Сравнително тестване", "Сравняване на две версии на страница, за да изберете по-добрата.", "A/B Testing", "Comparing two versions of a page to pick the better one."],
    ["Анализ на пътя на клиента", "Проследяване на пътя на клиента от първия контакт до покупката.", "Customer Journey Analysis", "Tracking the customer's path from first contact to purchase."],
    ["Топлинни карти (Hotjar и други)", "Показване къде точно кликат и гледат посетителите на сайта.", "Heatmap Analysis (Hotjar, etc.)", "Visualizing exactly where visitors click and look on your site."],
    ["Табла с ключови показатели", "Табло с ключовите показатели на бизнеса на едно място.", "KPI Dashboards", "A dashboard with your key business metrics in one place."],
    ["Прогнозни анализи", "Прогнози за бъдещи тенденции въз основа на текущите данни.", "Predictive Analytics", "Forecasts of future trends based on current data."],
    ["Консултации за големи обеми данни", "Съвети за работа с големи обеми бизнес данни.", "Big Data Consulting", "Advice on working with large volumes of business data."],
    ["Изграждане на хранилище за данни", "Централно хранилище за данните от различни системи.", "Data Warehouse Building", "A centralized repository for data from different systems."],
    ["Разработка на процеси за обработка на данни", "Автоматизиран процес за събиране и обработка на данни.", "ETL Pipeline Development", "An automated process for collecting and processing data."],
  ]},
  { id: "ai", icon: "cpu", name: { bg: "Изкуствен интелект и автоматизация", en: "AI & Automation" }, items: [
    ["Разработка на чат асистенти", "Автоматизиран асистент, който отговаря на въпроси на клиенти денонощно.", "Chatbot Development", "An automated assistant answering customer questions 24/7."],
    ["Създаване на съдържание с изкуствен интелект", "Използване на изкуствен интелект за създаване на текстове и изображения.", "AI Content Generation", "Using AI to create text and visuals."],
    ["Решения с машинно обучение", "Модели, които се учат от данни, за да подобряват процесите.", "Machine Learning Solutions", "Models that learn from data to improve processes."],
    ["Автоматизация на повтарящи се задачи", "Автоматизиране на повтарящи се ръчни задачи в бизнеса.", "RPA (Robotic Process Automation)", "Automating repetitive manual tasks in your business."],
    ["Гласови услуги с изкуствен интелект", "Гласови асистенти и разпознаване на реч за нуждите на бизнеса.", "Voice AI Services", "Voice assistants and speech recognition for business needs."],
    ["Системи за препоръки", "Системи, които препоръчват продукти или съдържание според интересите на клиента.", "Recommendation Systems", "Systems that recommend products or content by customer interest."],
    ["Изкуствен интелект за обслужване на клиенти", "Изкуствен интелект, който помага или поема обслужването на клиенти.", "AI for Customer Service", "AI supporting or automating your customer support."],
    ["Автоматизация на работни процеси", "Свързване на инструменти, за да текат задачите без ръчна намеса.", "Workflow Automation", "Connecting tools so tasks flow without manual work."],
    ["Прогнозни анализи с изкуствен интелект", "Прогнозиране на бъдещо поведение на клиентите с изкуствен интелект.", "AI Predictive Analytics", "Forecasting future customer behavior with AI."],
    ["Решения за разпознаване на изображения", "Разпознаване и анализ на изображения и видео с алгоритми.", "Computer Vision Solutions", "Recognizing and analyzing images and video with algorithms."],
    ["Вграждане на езикови модели в бизнеса", "Вграждане на езикови модели с изкуствен интелект в продукти и процеси.", "LLM Integration for Business", "Embedding language AI models into products and processes."],
    ["Разработка на самостоятелни асистенти", "Самостоятелни асистенти с изкуствен интелект, които изпълняват конкретни бизнес задачи.", "AI Agent Development", "Autonomous AI assistants performing specific business tasks."],
  ]},
  { id: "crm", icon: "users", name: { bg: "Клиентски системи и продажби", en: "CRM & Sales" }, items: [
    ["Настройка на CRM (HubSpot, Salesforce)", "Внедряване на система за управление на клиенти и продажби.", "CRM Setup (HubSpot, Salesforce)", "Implementing a system for managing customers and sales."],
    ["Изграждане на фуния за продажби", "Изграждане на ясен път от интерес до сключена сделка.", "Sales Funnel Building", "Building a clear path from interest to closed deal."],
    ["Системи за поддържане на интереса", "Автоматизирани поредици, които поддържат интереса на потенциалните клиенти.", "Lead Nurturing Systems", "Automated sequences that keep potential customers engaged."],
    ["Автоматизация на имейли", "Автоматични имейли, задействани от действията на клиента.", "Email Automation", "Automatic emails triggered by customer actions."],
    ["Управление на сделките", "Подреждане и проследяване на сделките през различните им етапи.", "Pipeline Management", "Organizing and tracking deals through their stages."],
    ["Настройка на софтуер за клиентска поддръжка", "Внедряване на система за организирано обслужване на клиенти.", "Customer Support Software Setup", "Implementing a system for organized customer support."],
    ["Системи за клиентска помощ", "Система за приемане и проследяване на клиентски запитвания.", "Help Desk Systems", "A system for receiving and tracking customer requests."],
    ["Консултации за по-силен търговски екип", "Съвети и инструменти, които помагат на търговския екип да затваря повече сделки.", "Sales Enablement Consulting", "Advice and tools helping your sales team close more deals."],
    ["Прехвърляне на клиентски данни между системи", "Прехвърляне на клиентски данни от една клиентска система в друга.", "CRM Migration Between Platforms", "Moving customer data from one CRM system to another."],
    ["Разработка на програма за лоялни клиенти", "Система за награждаване на лоялни клиенти с бонуси и отстъпки.", "Loyalty Program Development", "A system rewarding loyal customers with perks and discounts."],
  ]},
  { id: "pr", icon: "radio", name: { bg: "Връзки с обществеността и комуникации", en: "PR & Communications" }, items: [
    ["Стратегия за връзки с обществеността в интернет", "План за изграждане на публичния образ на марката в интернет.", "Online PR Strategy", "A plan for building your brand's public image online."],
    ["Комуникация при кризи", "Подготовка и реакция при ситуация, която застрашава името на марката.", "Crisis Communications", "Preparation and response for a reputation-threatening situation."],
    ["Връзка с медиите", "Свързване с журналисти и медии за отразяване на бизнеса ви.", "Media Outreach", "Connecting with journalists and media to cover your business."],
    ["Изработка на медиен комплект", "Готов комплект материали за медии за представяне на бизнеса.", "Press Kit Creation", "A ready media kit for presenting your business."],
    ["Управление на репутацията в интернет", "Следене и управление на това как изглежда марката ви в интернет.", "Online Reputation Management", "Monitoring and managing how your brand appears online."],
    ["Управление на отзиви (Google, Trustpilot)", "Управление на отзивите на клиентите в основните платформи.", "Review Management (Google, Trustpilot)", "Managing customer reviews across major platforms."],
    ["Партньорства с видеоблогъри и влиятелни личности", "Договаряне на партньорства с видеоблогъри за представяне на марката.", "Vlogger/Influencer Partnerships", "Arranging partnerships with vloggers to represent your brand."],
    ["Участия в подкасти", "Уговаряне на участия в подкасти за по-голяма видимост.", "Podcast PR Placement", "Arranging podcast appearances to boost visibility."],
    ["Консултации за награди и номинации", "Помощ при кандидатстване за бизнес награди и отличия.", "Awards & Nominations Consulting", "Help applying for business awards and recognitions."],
    ["Комуникация с инвеститори", "Комуникация с инвеститорите относно представянето на бизнеса.", "Investor Relations Communications", "Communication with investors about business performance."],
  ]},
  { id: "translation", icon: "languages", name: { bg: "Преводи и езиково приспособяване", en: "Translation & Localization" }, items: [
    ["Превод на уебсайт", "Превод на сайта на нужните ви езици.", "Website Translation", "Translating your site into the languages you need."],
    ["Приспособяване на съдържанието за нов пазар", "Приспособяване на съдържанието не само езиково, но и културно, за нов пазар.", "Content Localization", "Adapting content culturally, not just linguistically, for a new market."],
    ["SEO на няколко езика", "SEO стратегия, съобразена с всеки език и пазар поотделно.", "Multilingual SEO", "SEO strategy tailored to each language and market separately."],
    ["Субтитри за видео", "Превод и синхронизиране на субтитри към видео материал.", "Video Subtitles", "Translating and syncing subtitles for video content."],
    ["Превод на документи", "Превод на фирмени документи с внимание към термините.", "Document Translation", "Business document translation with attention to terminology."],
    ["Превод на приложения", "Превод и приспособяване на мобилно приложение за нов пазар.", "App Localization", "Translating and adapting a mobile app for a new market."],
    ["Заверен и клетвен превод", "Официален превод на документи с правна тежест.", "Certified/Sworn Translation", "Official translation of documents with legal weight."],
    ["Озвучаване на друг език", "Озвучаване на видео или реклама на нов език.", "Voice Dubbing", "Voicing video or ads in a new language."],
  ]},
  { id: "training", icon: "graduation-cap", name: { bg: "Обучения и консултации", en: "Training & Consulting" }, items: [
    ["Обучения по дигитален маркетинг", "Практическо обучение по дигитален маркетинг за екипа ви.", "Digital Marketing Training", "Hands-on digital marketing training for your team."],
    ["Обучения по SEO", "Обучение как сами да поддържате и подобрявате класирането на сайта.", "SEO Training", "Training to maintain and improve your site's ranking yourself."],
    ["Обучения за социални мрежи", "Обучение за самостоятелно управление на социалните мрежи на марката.", "Social Media Training", "Training to manage your brand's social media independently."],
    ["Консултации по информационни технологии", "Насоки за технологичните решения, подходящи за развитието на бизнеса.", "IT Consulting", "Guidance on the tech choices right for your business growth."],
    ["Онлайн семинари за клиенти", "Семинари в интернет, които обучават клиентите ви за продукта или темата.", "Client Webinars", "Online seminars educating your customers on a product or topic."],
    ["Индивидуални консултации", "Лични срещи, съобразени точно с вашите въпроси и цели.", "One-on-one Coaching", "Individual sessions tailored exactly to your questions and goals."],
    ["Фирмени обучения по информационни технологии", "Обучение на екипа за работа с нови системи и инструменти.", "Corporate IT Training", "Training your team to work with new systems and tools."],
    ["Изработка на онлайн курс", "Изграждане на платен онлайн курс от нулата за вашата аудитория.", "Online Course Creation", "Building a paid online course from scratch for your audience."],
  ]},
  { id: "maintenance", icon: "wrench", name: { bg: "Абонаментни услуги и поддръжка", en: "Subscription & Maintenance" }, items: [
    ["Месечна поддръжка на сайт", "Редовни технически грижи, за да работи сайтът ви без проблеми.", "Monthly Website Maintenance", "Ongoing technical care so your site runs without issues."],
    ["Сайт срещу абонамент", "Сайт на абонамент — всичко включено срещу фиксирана месечна цена.", "Website-as-a-Service (WaaS)", "A subscription site — everything included for one fixed monthly fee."],
    ["Управляван хостинг", "Хостинг, за който се грижим ние вместо вас.", "Managed Hosting", "Hosting that we take care of for you."],
    ["Съдържание срещу абонамент", "Редовно ново съдържание за сайта или социалните мрежи срещу абонамент.", "Content-as-a-Service", "Fresh site or social content on a regular subscription."],
    ["SEO срещу абонамент", "Непрекъсната грижа за SEO срещу месечен абонамент.", "SEO-as-a-Service", "Ongoing SEO care on a monthly subscription."],
    ["Социални мрежи срещу абонамент", "Управление на социалните мрежи срещу месечен абонамент.", "Social Media-as-a-Service", "Social media management on a monthly subscription."],
    ["Пакети за техническо обновяване", "Еднократно обновяване на остарели части от сайта или системата.", "Technical Upgrade Packages", "A one-time upgrade of outdated parts of a site or system."],
    ["Денонощно наблюдение", "Постоянно наблюдение на сайта за проблеми и прекъсвания.", "24/7 Monitoring Service", "Constant monitoring of your site for issues and downtime."],
  ]},
  { id: "legal", icon: "scale", name: { bg: "GDPR и правни услуги", en: "GDPR & Legal" }, items: [
    ["Политика по GDPR и бисквитки", "Задължителните документи за поверителност и съгласие за бисквитки.", "GDPR Policy & Cookies", "The required privacy policy and cookie consent documents."],
    ["Изработка на общи условия", "Ясни правила за ползване на сайта или услугата ви.", "Terms of Service Drafting", "Clear rules for using your site or service."],
    ["Политика за поверителност", "Документ, който обяснява как се обработват личните данни на посетителите.", "Privacy Policy", "A document explaining how visitors' personal data is handled."],
    ["Договор за обработване на лични данни", "Договор, който урежда обработването на лични данни между страни.", "Data Processing Agreement (DPA)", "An agreement governing personal data processing between parties."],
    ["Договори за услуги", "Изготвяне на договори между вас и вашите клиенти.", "Service Agreements", "Drafting contracts between you and your clients."],
    ["Консултация за регистрация на търговска марка", "Насоки за регистрация и защита на търговската ви марка.", "Trademark Registration Consulting", "Guidance on registering and protecting your trademark."],
    ["Данни за собственика на сайта", "Задължителна информация за собственика на сайта според закона.", "Imprint/Owner Disclosure", "Legally required owner information for the site."],
    ["Управление на съгласието за бисквитки", "Система за управление на съгласието за бисквитки на сайта.", "Cookie Consent Management", "A system for managing cookie consent on your site."],
    ["Одит за съответствие с GDPR", "Проверка доколко бизнесът ви отговаря на изискванията на GDPR.", "GDPR Audit", "Checking how well your business complies with GDPR."],
    ["Консултация за интелектуална собственост", "Съвети за защита на авторски права и интелектуална собственост.", "Intellectual Property Consulting", "Advice on protecting copyright and intellectual property."],
    ["Условия за връщане и рекламации", "Ясни правила за връщане на стоки и решаване на рекламации.", "Returns/Complaints Terms", "Clear rules for returns and handling complaints."],
  ]},
];

// Обединяване в един общ масив от услуги
const SERVICES = [];
CATS.forEach((c) => {
  c.items.forEach((it, i) => {
    SERVICES.push({
      id: `${c.id}-${i}`, cat: c.id,
      name: { bg: it[0], en: it[2] },
      desc: { bg: it[1], en: it[3] },
    });
  });
});
function catOf(id) { return CATS.find((c) => c.id === id); }
const TOTAL_SERVICES = SERVICES.length;
