/* Hackera — data for the static site (bilingual: bg/en) */
const CATS = [
  { id: "web", icon: "globe", name: { bg: "Уеб разработка", en: "Web Development" }, items: [
    ["Изработка на фирмен сайт", "Модерен сайт с всички основни страници, готов да представя бизнеса ви онлайн.", "Business Website Development", "A modern site with all core pages, ready to represent your business online."],
    ["Целеви страници", "Отделна страница, фокусирана върху едно предложение или кампания, за максимална конверсия.", "Landing Pages", "A dedicated page focused on one offer or campaign, built for maximum conversion."],
    ["Онлайн магазини (e-commerce)", "Пълноценен магазин с каталог, количка и разплащане за продажба онлайн.", "Online Stores (E-commerce)", "A full store with catalog, cart and checkout for selling online."],
    ["WordPress разработка", "Изграждане на сайт върху WordPress — гъвкав и лесен за самостоятелна поддръжка.", "WordPress Development", "Building a site on WordPress — flexible and easy to maintain yourself."],
    ["Shopify разработка", "Онлайн магазин върху Shopify, готов за бързо стартиране на продажби.", "Shopify Development", "An online store on Shopify, ready to start selling fast."],
    ["Custom уеб приложения", "Уеб приложение, изградено по мярка за специфичен бизнес процес.", "Custom Web Apps", "A web application built to fit a specific business process."],
    ["Уеб дизайн (UI/UX)", "Визуален дизайн на интерфейса, съобразен с това как потребителите реално го ползват.", "Web Design (UI/UX)", "Interface design built around how people actually use it."],
    ["Responsive/мобилна адаптация", "Адаптиране на съществуващ сайт, за да изглежда добре на всяко устройство.", "Responsive/Mobile Adaptation", "Adapting an existing site to look great on every device."],
    ["Поддръжка на сайтове", "Редовни технически грижи, за да работи сайтът ви гладко и сигурно.", "Website Maintenance", "Ongoing technical care so your site runs smoothly and safely."],
    ["Миграция на сайтове", "Прехвърляне на сайт към нов хостинг или платформа без прекъсване.", "Website Migration", "Moving a site to new hosting or a new platform without downtime."],
    ["Оптимизация на скорост", "Ускоряване на зареждането на сайта за по-добро изживяване и SEO.", "Speed Optimization", "Faster load times for a better experience and better SEO."],
    ["API интеграции", "Свързване на сайта с външни системи и услуги чрез програмни интерфейси.", "API Integrations", "Connecting your site to external systems and services."],
    ["Разработка на плъгин", "Изработка на разширение по поръчка за конкретна функционалност на сайта.", "Plugin Development", "A custom plugin built for a specific site feature."],
    ["Теми за WordPress", "Дизайн на тема по поръчка за WordPress сайт.", "WordPress Themes", "Custom WordPress theme design."],
    ["Progressive Web Apps (PWA)", "Сайт, който се държи като приложение — работи офлайн и се инсталира.", "Progressive Web Apps (PWA)", "A site that behaves like an app — works offline and installs."],
    ["A/B тестване на целеви страници", "Тестване на различни версии на страница, за да откриете коя продава повече.", "Landing Page A/B Testing", "Testing page versions to find out which one converts better."],
    ["Чат бот за сайт", "Автоматизиран чат, който отговаря на клиенти директно на сайта.", "Website Chatbots", "An automated chat that answers customers right on your site."],
    ["Онлайн система за резервации", "Календар за резервации, през който клиенти сами си запазват час.", "Online Booking Systems", "A booking calendar customers use to schedule themselves."],
    ["Платформи за абонамент", "Система за платено съдържание или услуги на абонамент.", "Subscription Platforms", "A system for paid content or services on subscription."],
    ["Сайтове с платено членство", "Затворена зона за регистрирани потребители с ексклузивно съдържание.", "Membership Sites", "A gated area for registered users with exclusive content."],
  ]},
  { id: "seo", icon: "trending-up", name: { bg: "SEO услуги", en: "SEO Services" }, items: [
    ["SEO одит", "Пълен преглед на сайта, за да откриете какво пречи на класирането му.", "SEO Audit", "A full review of the site to find what's holding back its ranking."],
    ["On-page SEO", "Оптимизация на съдържанието и структурата на самите страници за търсачките.", "On-page SEO", "Optimizing content and structure of pages for search engines."],
    ["Off-page SEO (линк билдинг)", "Изграждане на препратки от други сайтове, за да расте авторитетът ви.", "Off-page SEO (Link Building)", "Building links from other sites to grow your authority."],
    ["Технически SEO", "Отстраняване на технически проблеми, които пречат на индексирането от Google.", "Technical SEO", "Fixing technical issues that block Google from indexing you."],
    ["Local SEO (Google Business Profile)", "Оптимизация за локално търсене, за да ви намират клиенти във вашия град.", "Local SEO (Google Business Profile)", "Optimizing for local search so nearby customers find you."],
    ["Keyword проучване", "Откриване на точните думи, които клиентите ви търсят в Google.", "Keyword Research", "Finding the exact words your customers search for."],
    ["Конкурентен анализ", "Преглед на стратегиите на конкурентите, за да откриете възможности за вас.", "Competitor Analysis", "Reviewing competitor strategies to find opportunities for you."],
    ["SEO копирайтинг", "Текстове, писани едновременно за читателя и за търсачките.", "SEO Copywriting", "Content written for readers and search engines at once."],
    ["Маркиране на структурирани данни", "Код, който помага на Google да разбира по-добре съдържанието на страницата.", "Schema Markup (Structured Data)", "Code that helps Google better understand your page content."],
    ["Мобилно SEO", "Оптимизация специално за представянето на сайта в мобилно търсене.", "Mobile SEO", "Optimization focused on mobile search performance."],
    ["Гласово търсене оптимизация", "Адаптиране на съдържанието за въпроси, зададени гласово към асистенти.", "Voice Search Optimization", "Adapting content for questions asked to voice assistants."],
    ["E-commerce SEO", "SEO стратегия специално за продуктови страници и категории в онлайн магазин.", "E-commerce SEO", "SEO strategy specifically for product and category pages."],
    ["Международно SEO", "Настройка на сайта за класиране в няколко държави и езика едновременно.", "International SEO", "Setting up a site to rank across multiple countries and languages."],
    ["SEO мониторинг и отчети", "Редовно проследяване на позициите и трафика с ясни отчети.", "SEO Monitoring & Reports", "Ongoing tracking of rankings and traffic with clear reports."],
    ["Content gap анализ", "Откриване на теми, които конкурентите покриват, а вие — все още не.", "Content Gap Analysis", "Finding topics competitors cover that you don't yet."],
  ]},
  { id: "marketing", icon: "megaphone", name: { bg: "Дигитален маркетинг", en: "Digital Marketing" }, items: [
    ["PPC реклами (Google Ads)", "Платени реклами в Google, които се появяват точно при търсене на вашата услуга.", "PPC Ads (Google Ads)", "Paid ads that appear exactly when people search for your service."],
    ["Реклами в Facebook/Instagram", "Таргетирани реклами към точната аудитория в Meta платформите.", "Facebook/Instagram Ads", "Targeted ads reaching the right audience on Meta platforms."],
    ["Реклами в TikTok", "Кратки видео реклами, достигащи по-млада аудитория в TikTok.", "TikTok Ads", "Short video ads reaching a younger audience on TikTok."],
    ["Реклами в LinkedIn", "Реклами, насочени към професионалисти и B2B аудитория в LinkedIn.", "LinkedIn Ads", "Ads targeting professionals and B2B audiences on LinkedIn."],
    ["Реклами в YouTube", "Видео реклами преди или по време на съдържание в YouTube.", "YouTube Ads", "Video ads shown before or during YouTube content."],
    ["Кампании за ретаргетинг", "Реклами, насочени към хора, посетили сайта ви, но не завършили покупка.", "Retargeting Campaigns", "Ads aimed at people who visited but didn't convert."],
    ["Дисплейни реклами", "Банерни реклами, показвани в мрежа от партньорски сайтове.", "Display Ads", "Banner ads shown across a network of partner sites."],
    ["Програматично рекламиране", "Автоматизирано купуване на рекламно пространство в реално време.", "Programmatic Advertising", "Automated buying of ad space in real time."],
    ["Афилиейт маркетинг", "Партньорска програма, в която трети страни продават срещу комисионна.", "Affiliate Marketing", "A partner program where third parties sell for a commission."],
    ["Инфлуенсър маркетинг", "Партньорства с инфлуенсъри за представяне на продукта пред тяхната аудитория.", "Influencer Marketing", "Partnering with influencers to reach their audience."],
    ["Имейл маркетинг", "Кампании по имейл за задържане и активиране на клиенти.", "Email Marketing", "Campaigns for retaining and re-engaging customers."],
    ["СМС маркетинг", "Кратки текстови съобщения за промоции и напомняния до клиенти.", "SMS Marketing", "Short text messages for promotions and reminders."],
    ["WhatsApp маркетинг кампании", "Директна комуникация с клиенти през WhatsApp за оферти и поддръжка.", "WhatsApp Marketing", "Direct customer communication via WhatsApp for offers and support."],
    ["Маркетингова автоматизация", "Автоматизирани поредици от съобщения, задействани от поведението на клиента.", "Marketing Automation", "Automated message sequences triggered by customer behavior."],
    ["Привличане на потенциални клиенти", "Кампании, насочени специално към набиране на нови потенциални клиенти.", "Lead Generation", "Campaigns focused specifically on gathering new leads."],
    ["Conversion Rate Optimization (CRO)", "Подобряване на сайта, за да превръща повече посетители в клиенти.", "Conversion Rate Optimization (CRO)", "Improving the site to turn more visitors into customers."],
    ["Growth hacking", "Бързи, евтини експерименти за откриване на канали за растеж.", "Growth Hacking", "Fast, low-cost experiments to find growth channels."],
    ["Маркетинг стратегия", "Цялостен план за това как да достигнете и убедите аудиторията си.", "Marketing Strategy", "A full plan for reaching and convincing your audience."],
    ["Marketing одит", "Преглед на текущите маркетинг усилия и къде се губят пари и резултати.", "Marketing Audit", "A review of current marketing efforts and where results are lost."],
    ["Ремаркетинг стратегии", "Стратегия за връщане на посетители, които вече са проявили интерес.", "Remarketing Strategies", "A strategy for bringing back visitors who showed interest."],
  ]},
  { id: "social", icon: "share-2", name: { bg: "Социални медии", en: "Social Media" }, items: [
    ["Управление на социални мрежи (SMM)", "Ежедневно управление на профилите ви в социалните мрежи.", "Social Media Management (SMM)", "Day-to-day management of your social media profiles."],
    ["Създаване на съдържание за социални мрежи", "Планиране и изработка на публикации, съобразени с всяка платформа.", "Social Media Content Creation", "Planning and creating posts tailored to each platform."],
    ["Instagram Reels продукция", "Кратки вертикални видеа, направени да работят добре в Instagram.", "Instagram Reels Production", "Short vertical videos built to perform well on Instagram."],
    ["TikTok видео продукция", "Видео съдържание, заснето и монтирано специално за TikTok.", "TikTok Video Production", "Video content shot and edited specifically for TikTok."],
    ["Facebook страница управление", "Поддръжка и развитие на бизнес страницата ви във Facebook.", "Facebook Page Management", "Ongoing management and growth of your Facebook business page."],
    ["LinkedIn company page управление", "Управление на фирмения профил и присъствие в LinkedIn.", "LinkedIn Company Page Management", "Managing your company profile and presence on LinkedIn."],
    ["Social media стратегия", "План за това какво, кога и защо публикувате в социалните мрежи.", "Social Media Strategy", "A plan for what, when and why you post on social media."],
    ["Community management", "Активна комуникация и изграждане на общност около бранда ви.", "Community Management", "Active engagement and community-building around your brand."],
    ["Модерация на коментари", "Наблюдение и отговаряне на коментари под публикациите ви.", "Comment Moderation", "Monitoring and responding to comments on your posts."],
    ["Social listening", "Проследяване какво се говори за бранда ви онлайн.", "Social Listening", "Tracking what's being said about your brand online."],
    ["Хаштаг стратегия", "Изследване и подбор на хаштагове за по-голяма видимост.", "Hashtag Strategy", "Research and selection of hashtags for greater reach."],
    ["Social media одит", "Преглед на профилите ви и препоръки за подобрение.", "Social Media Audit", "A review of your profiles with improvement recommendations."],
    ["Influencer outreach", "Издирване и договаряне с подходящи инфлуенсъри за бранда ви.", "Influencer Outreach", "Finding and negotiating with the right influencers for your brand."],
    ["UGC кампании", "Кампании, насърчаващи клиентите сами да създават съдържание за бранда.", "UGC Campaigns", "Campaigns that encourage customers to create content for your brand."],
    ["Social media криза мениджмънт", "Бърза и премерена реакция при негативна вълна в социалните мрежи.", "Social Media Crisis Management", "A fast, measured response to a negative wave online."],
  ]},
  { id: "content", icon: "pen-tool", name: { bg: "Съдържание и копирайтинг", en: "Content & Copywriting" }, items: [
    ["Копирайтинг за сайтове", "Текстове за всяка страница на сайта, писани да убеждават и информират.", "Website Copywriting", "Page-by-page copy written to persuade and inform."],
    ["Блог статии", "Редовни статии, които привличат трафик и изграждат авторитет.", "Blog Articles", "Regular articles that drive traffic and build authority."],
    ["SEO текстове", "Съдържание, оптимизирано около конкретни търсения на клиентите ви.", "SEO Content", "Content optimized around your customers' actual searches."],
    ["Продуктови описания", "Кратки, продаващи описания за всеки продукт в магазина ви.", "Product Descriptions", "Short, persuasive copy for every product in your store."],
    ["Имейл текстове", "Текстове за имейл кампании, писани за отваряне и действие.", "Email Copy", "Email campaign copy written to be opened and acted on."],
    ["Скриптове за реклами", "Кратки, ударни текстове за видео и аудио реклами.", "Ad Scripts", "Short, punchy scripts for video and audio ads."],
    ["Технически писане", "Ясни ръководства и документация за продукт или услуга.", "Technical Writing", "Clear guides and documentation for a product or service."],
    ["Storytelling за брандове", "Изграждане на разказ около бранда, който остава в паметта.", "Brand Storytelling", "Building a brand narrative that sticks in memory."],
    ["Съдържание за социални мрежи", "Текстове, съобразени с тона и формата на всяка платформа.", "Social Media Copy", "Copy tailored to the tone and format of each platform."],
    ["Whitepaper писане", "Задълбочен документ, показващ експертиза по конкретна тема.", "Whitepaper Writing", "An in-depth document showcasing expertise on a topic."],
    ["Case study писане", "Разказ за конкретен успешен проект с измерими резултати.", "Case Study Writing", "A write-up of a successful project with measurable results."],
    ["Press release писане", "Официално съобщение за медиите при важна новина на бизнеса.", "Press Release Writing", "An official media statement for important business news."],
    ["Newsletter съдържание", "Редовен бюлетин, който държи клиентите ви информирани и ангажирани.", "Newsletter Content", "A regular newsletter that keeps customers informed and engaged."],
    ["Ghostwriting", "Писане на съдържание от името на друг автор или бранд.", "Ghostwriting", "Writing content under another author's or brand's name."],
    ["Транскрипция на аудио/видео", "Превръщане на говорено съдържание в писмен текст.", "Audio/Video Transcription", "Turning spoken content into written text."],
  ]},
  { id: "design", icon: "palette", name: { bg: "Дизайн и графика", en: "Design & Graphics" }, items: [
    ["Лого дизайн", "Ясен, запомнящ се знак, който представя бранда ви визуално.", "Logo Design", "A clear, memorable mark that represents your brand visually."],
    ["Брандинг пакети", "Цялостен визуален пакет — цветове, шрифтове и стил на бранда.", "Branding Packages", "A full visual package — colors, fonts and brand style."],
    ["Визуална идентичност", "Единна визия във всички материали на бизнеса ви.", "Visual Identity", "A consistent look across all of your business materials."],
    ["Дизайн на визитки", "Професионални визитки, съобразени с визуалния стил на бранда.", "Business Card Design", "Professional cards matching your brand's visual style."],
    ["Брошури и флаери", "Печатни материали за представяне на бизнеса или конкретна оферта.", "Brochures & Flyers", "Print materials to present your business or an offer."],
    ["Banner дизайн", "Рекламни банери за сайтове и социални мрежи.", "Banner Design", "Ad banners for websites and social media."],
    ["Social media графики", "Готови визуални шаблони за публикации в социалните мрежи.", "Social Media Graphics", "Ready-made visual templates for social media posts."],
    ["Presentation дизайн", "Професионална презентация за клиенти, инвеститори или партньори.", "Presentation Design", "A professional deck for clients, investors or partners."],
    ["Инфографики", "Визуализация на данни и информация в лесен за възприемане формат.", "Infographics", "Turning data and information into an easy-to-read visual."],
    ["Illustration услуги", "Оригинални илюстрации по поръчка за сайт, продукт или кампания.", "Illustration Services", "Original custom illustrations for a site, product or campaign."],
    ["Packaging дизайн", "Дизайн на опаковка, който изпъква на рафта.", "Packaging Design", "Package design that stands out on the shelf."],
    ["UI дизайн за апликации", "Визуален дизайн на екраните в мобилно или уеб приложение.", "App UI Design", "Visual design of the screens in a mobile or web app."],
    ["UX проучване и wireframing", "Проучване на потребителското поведение и скициране на структурата преди дизайн.", "UX Research & Wireframing", "Researching user behavior and sketching structure before design."],
    ["Icon дизайн", "Комплект икони по поръчка, съобразени със стила на бранда.", "Icon Design", "A custom icon set matching your brand's style."],
    ["Email template дизайн", "Дизайн на шаблон за имейл кампании, готов за многократна употреба.", "Email Template Design", "A reusable template design for email campaigns."],
  ]},
  { id: "video", icon: "video", name: { bg: "Видео и аудио продукция", en: "Video & Audio Production" }, items: [
    ["Промо видеа", "Кратко видео, представящо продукт или услуга по атрактивен начин.", "Promo Videos", "A short video presenting a product or service attractively."],
    ["Анимационни видеа", "Анимирано видео за обяснение на идея или продукт.", "Animated Videos", "An animated video explaining an idea or product."],
    ["Explainer видеа", "Кратко видео, обясняващо как работи продукт или услуга.", "Explainer Videos", "A short video explaining how a product or service works."],
    ["Видео монтаж", "Професионален монтаж на заснет видео материал.", "Video Editing", "Professional editing of raw video footage."],
    ["Motion graphics", "Анимирани графични елементи за видео и реклами.", "Motion Graphics", "Animated graphic elements for video and ads."],
    ["Подкаст продукция", "Запис, монтаж и публикуване на подкаст епизоди.", "Podcast Production", "Recording, editing and publishing podcast episodes."],
    ["Гласов запис (voiceover)", "Професионален дублаж или разказ за видео и реклами.", "Voiceover Recording", "Professional voiceover or narration for video and ads."],
    ["Музикална продукция за реклами", "Оригинална или подбрана музика за видео и аудио реклами.", "Music Production for Ads", "Original or licensed music for video and audio ads."],
    ["Live streaming услуги", "Организация и техническа поддръжка на пряко излъчване.", "Live Streaming Services", "Organization and technical support for live broadcasts."],
    ["Webinar продукция", "Организация и провеждане на онлайн семинар за аудиторията ви.", "Webinar Production", "Organizing and running an online seminar for your audience."],
    ["Видео за социални мрежи", "Кратки видеа, форматирани специално за социалните платформи.", "Social Media Video", "Short videos formatted specifically for social platforms."],
    ["Corporate видеа", "Фирмено видео, представящо екип, ценности и дейност.", "Corporate Videos", "A company video showcasing team, values and work."],
    ["Product демо видеа", "Видео, показващо продукта в реална употреба.", "Product Demo Videos", "A video showing the product in real use."],
    ["360° видео", "Панорамно видео, позволяващо на зрителя да разглежда сцената свободно.", "360° Video", "Panoramic video letting the viewer explore the scene freely."],
    ["Drone видеография", "Въздушни кадри, заснети с дрон за уникална гледна точка.", "Drone Videography", "Aerial footage shot with a drone for a unique angle."],
  ]},
  { id: "photo", icon: "camera", name: { bg: "Фотография", en: "Photography" }, items: [
    ["Продуктова фотография", "Професионални снимки на продукти за сайт и социални мрежи.", "Product Photography", "Professional product photos for your site and social media."],
    ["Корпоративна фотография", "Фирмени снимки на екип, офис и събития.", "Corporate Photography", "Business photos of your team, office and events."],
    ["Event фотография", "Заснемане на бизнес събития, конференции и партита.", "Event Photography", "Coverage of business events, conferences and parties."],
    ["Food фотография", "Апетитни снимки на храна за менюта и социални мрежи.", "Food Photography", "Appetizing food photos for menus and social media."],
    ["Real estate фотография", "Професионални снимки на имоти за обяви и реклама.", "Real Estate Photography", "Professional property photos for listings and ads."],
    ["Headshot фотография", "Професионален портрет за екипа, сайта или LinkedIn.", "Headshot Photography", "A professional portrait for your team, site or LinkedIn."],
    ["Stock фотография услуги", "Изработка на оригинални снимки за многократна употреба в материали.", "Stock Photography Services", "Original photos produced for repeated use in materials."],
    ["Сватбена фотография", "Пълно заснемане на сватбено тържество от началото до края.", "Wedding Photography", "Full coverage of a wedding from start to finish."],
    ["Фотография за ресторантско меню", "Снимки на ястия, изградени специално за печатно или дигитално меню.", "Restaurant Menu Photography", "Dish photos built specifically for a print or digital menu."],
    ["Aerial/дрон фотография", "Въздушни снимки на имоти, събития или локации.", "Aerial/Drone Photography", "Aerial photos of properties, events or locations."],
  ]},
  { id: "mobile", icon: "smartphone", name: { bg: "Мобилни приложения", en: "Mobile Apps" }, items: [
    ["iOS разработка", "Мобилно приложение, изградено специално за iPhone и iPad.", "iOS Development", "A mobile app built specifically for iPhone and iPad."],
    ["Android разработка", "Мобилно приложение, изградено специално за Android устройства.", "Android Development", "A mobile app built specifically for Android devices."],
    ["Cross-platform (React Native/Flutter)", "Едно приложение, работещо едновременно на iOS и Android.", "Cross-platform (React Native/Flutter)", "One app that runs on both iOS and Android."],
    ["App Store оптимизация (ASO)", "Оптимизация на страницата на приложението за повече изтегляния.", "App Store Optimization (ASO)", "Optimizing your app store listing for more downloads."],
    ["Mobile app дизайн", "Визуален дизайн на екраните и потока в приложението.", "Mobile App Design", "Visual design of the screens and flow in your app."],
    ["App поддръжка и ъпдейти", "Редовни актуализации и техническа поддръжка на приложението.", "App Maintenance & Updates", "Ongoing updates and technical support for your app."],
    ["Push notification системи", "Настройка на известия, които връщат потребителите в приложението.", "Push Notification Systems", "Setting up notifications that bring users back to the app."],
    ["Wearables приложения", "Приложения за смарт часовници и други носими устройства.", "Wearable Apps", "Apps for smartwatches and other wearable devices."],
    ["In-app покупки интеграция", "Вграждане на разплащания и абонаменти вътре в приложението.", "In-app Purchases Integration", "Building payments and subscriptions right into the app."],
    ["App аналитика интеграция", "Проследяване на поведението на потребителите вътре в приложението.", "App Analytics Integration", "Tracking user behavior inside the app."],
  ]},
  { id: "ecommerce", icon: "shopping-cart", name: { bg: "E-commerce", en: "E-commerce" }, items: [
    ["Онлайн магазин настройка", "Пълна настройка на онлайн магазин, готов за първите продажби.", "Online Store Setup", "A full online store setup, ready for its first sales."],
    ["Продуктов каталог управление", "Организация и поддръжка на продуктите в магазина.", "Product Catalog Management", "Organizing and maintaining the products in your store."],
    ["Payment gateway интеграция", "Свързване на магазина с системи за онлайн разплащане.", "Payment Gateway Integration", "Connecting your store to online payment systems."],
    ["Инвентар мениджмънт системи", "Система за проследяване на наличностите в реално време.", "Inventory Management Systems", "A system for tracking stock levels in real time."],
    ["Shopping cart оптимизация", "Подобряване на количката за пазаруване, за да се завършват повече поръчки.", "Shopping Cart Optimization", "Improving the cart to complete more orders."],
    ["Marketplace листинг (Amazon, eBay)", "Публикуване и управление на продукти в големи онлайн платформи.", "Marketplace Listing (Amazon, eBay)", "Publishing and managing products on major online platforms."],
    ["Dropshipping консултации", "Съвети и настройка за модел на продажба без собствен склад.", "Dropshipping Consulting", "Advice and setup for a no-inventory sales model."],
    ["E-commerce фотография", "Продуктови снимки, оптимизирани за онлайн магазин.", "E-commerce Photography", "Product photos optimized for an online store."],
    ["Checkout оптимизация", "Опростяване на процеса на плащане за по-малко изоставени колички.", "Checkout Optimization", "Simplifying checkout for fewer abandoned carts."],
    ["Abandoned cart кампании", "Автоматични напомняния до клиенти, изоставили количката си.", "Abandoned Cart Campaigns", "Automatic reminders to customers who left their cart."],
    ["Multi-currency настройка", "Настройка на магазина за продажби в няколко валути.", "Multi-currency Setup", "Setting up your store to sell in multiple currencies."],
    ["Subscription commerce платформи", "Система за продажба на продукти или услуги на абонамент.", "Subscription Commerce Platforms", "A system for selling products or services on subscription."],
  ]},
  { id: "cloud", icon: "cloud", name: { bg: "IT и облачни услуги", en: "IT & Cloud Services" }, items: [
    ["Cloud hosting (AWS, Azure, Google Cloud)", "Хостинг на инфраструктура в облак, съобразен с нуждите на бизнеса.", "Cloud Hosting (AWS, Azure, Google Cloud)", "Cloud infrastructure hosting tailored to your business needs."],
    ["Сървърна администрация", "Управление и поддръжка на сървъри, на които работи сайтът ви.", "Server Administration", "Managing and maintaining the servers your site runs on."],
    ["Домейн регистрация", "Регистрация и управление на домейн името на бизнеса ви.", "Domain Registration", "Registering and managing your business's domain name."],
    ["Email хостинг", "Професионални имейл адреси на собствения ви домейн.", "Email Hosting", "Professional email addresses on your own domain."],
    ["Backup решения", "Автоматични резервни копия на данните ви за спокойствие.", "Backup Solutions", "Automatic backups of your data for peace of mind."],
    ["VPN услуги", "Сигурна отдалечена връзка към фирмената мрежа.", "VPN Services", "A secure remote connection to your company network."],
    ["DevOps услуги", "Автоматизация на процесите по разработка и пускане на софтуер.", "DevOps Services", "Automating your development and release processes."],
    ["CI/CD настройка", "Автоматизирано тестване и пускане на нови версии на софтуера.", "CI/CD Setup", "Automated testing and release of new software versions."],
    ["Database management", "Управление, оптимизация и сигурност на базите данни.", "Database Management", "Managing, optimizing and securing your databases."],
    ["IT консултации", "Съвети за технологичните решения, най-подходящи за бизнеса ви.", "IT Consulting", "Advice on the technology choices that fit your business."],
    ["Мигриране към облак", "Прехвърляне на съществуваща инфраструктура в облачна среда.", "Cloud Migration", "Moving existing infrastructure into a cloud environment."],
    ["Serverless архитектура", "Изграждане на приложения без нужда от управление на сървъри.", "Serverless Architecture", "Building applications without managing servers."],
  ]},
  { id: "security", icon: "shield-check", name: { bg: "Киберсигурност", en: "Cybersecurity" }, items: [
    ["Security одит", "Цялостна проверка на системите ви за уязвимости.", "Security Audit", "A full review of your systems for vulnerabilities."],
    ["Penetration testing", "Контролирана симулация на атака, за да откриете слаби места.", "Penetration Testing", "A controlled simulated attack to find weak spots."],
    ["Firewall настройка", "Защита на мрежата ви от нежелан достъп.", "Firewall Setup", "Protecting your network from unwanted access."],
    ["SSL сертификати", "Криптирана връзка между сайта и посетителите му.", "SSL Certificates", "An encrypted connection between your site and its visitors."],
    ["Malware премахване", "Откриване и премахване на злонамерен код от сайт или система.", "Malware Removal", "Finding and removing malicious code from a site or system."],
    ["Password мениджмънт системи", "Сигурно съхранение и управление на пароли в организацията.", "Password Management Systems", "Secure storage and management of passwords in your org."],
    ["Two-factor автентикация настройка", "Допълнителен слой сигурност при вход в системите ви.", "Two-factor Authentication Setup", "An extra layer of security when logging into your systems."],
    ["Incident response", "Бърза реакция и възстановяване след инцидент със сигурността.", "Incident Response", "Fast reaction and recovery after a security incident."],
    ["DDoS защита", "Защита срещу претоварващи атаки, насочени към сайта ви.", "DDoS Protection", "Protection against overload attacks targeting your site."],
    ["Мрежова сигурност одит", "Преглед на цялата мрежова инфраструктура за рискове.", "Network Security Audit", "A review of your entire network infrastructure for risk."],
    ["Ransomware защита", "Мерки срещу зловреден софтуер, криптиращ данните ви за откуп.", "Ransomware Protection", "Measures against malware that encrypts your data for ransom."],
    ["Bug bounty програма координация", "Организиране на програма, награждаваща откриването на уязвимости.", "Bug Bounty Program Coordination", "Organizing a program that rewards finding vulnerabilities."],
  ]},
  { id: "data", icon: "bar-chart-3", name: { bg: "Данни и анализ", en: "Data & Analytics" }, items: [
    ["Google Analytics настройка", "Настройка на проследяване на трафика и поведението на сайта ви.", "Google Analytics Setup", "Setting up tracking for your site's traffic and behavior."],
    ["Data визуализация", "Превръщане на суровите данни в ясни визуални отчети.", "Data Visualization", "Turning raw data into clear visual reports."],
    ["Business intelligence", "Системи за анализ на данни в подкрепа на бизнес решенията.", "Business Intelligence", "Data analysis systems supporting business decisions."],
    ["Data анализ и отчети", "Редовни отчети, показващи какво работи и какво — не.", "Data Analysis & Reports", "Regular reports showing what's working and what isn't."],
    ["A/B тестване", "Сравняване на две версии на страница, за да изберете по-добрата.", "A/B Testing", "Comparing two versions of a page to pick the better one."],
    ["Customer journey анализ", "Проследяване на пътя на клиента от първия контакт до покупка.", "Customer Journey Analysis", "Tracking the customer's path from first contact to purchase."],
    ["Heatmap анализ (Hotjar и др.)", "Визуализация къде точно кликат и гледат посетителите на сайта.", "Heatmap Analysis (Hotjar, etc.)", "Visualizing exactly where visitors click and look on your site."],
    ["KPI дашборди", "Табло с ключовите показатели на бизнеса на едно място.", "KPI Dashboards", "A dashboard with your key business metrics in one place."],
    ["Predictive анализ", "Прогнози за бъдещи тенденции въз основа на текущи данни.", "Predictive Analytics", "Forecasts of future trends based on current data."],
    ["Big data консултации", "Съвети за работа с големи обеми бизнес данни.", "Big Data Consulting", "Advice on working with large volumes of business data."],
    ["Data warehouse изграждане", "Централизирано хранилище за данните от различни системи.", "Data Warehouse Building", "A centralized repository for data from different systems."],
    ["ETL pipeline разработка", "Автоматизиран процес за събиране и обработка на данни.", "ETL Pipeline Development", "An automated process for collecting and processing data."],
  ]},
  { id: "ai", icon: "cpu", name: { bg: "Изкуствен интелект и автоматизация", en: "AI & Automation" }, items: [
    ["Chatbot разработка", "Автоматизиран асистент, отговарящ на въпроси на клиенти 24/7.", "Chatbot Development", "An automated assistant answering customer questions 24/7."],
    ["AI-съдържание генериране", "Използване на изкуствен интелект за създаване на текстове и визии.", "AI Content Generation", "Using AI to create text and visuals."],
    ["Machine learning решения", "Модели, които се учат от данни, за да подобряват процеси.", "Machine Learning Solutions", "Models that learn from data to improve processes."],
    ["RPA (Robotic Process Automation)", "Автоматизация на повтарящи се ръчни задачи в бизнеса.", "RPA (Robotic Process Automation)", "Automating repetitive manual tasks in your business."],
    ["Voice AI услуги", "Гласови асистенти и разпознаване на реч за бизнес нужди.", "Voice AI Services", "Voice assistants and speech recognition for business needs."],
    ["Recommendation системи", "Системи, препоръчващи продукти или съдържание според интересите на клиента.", "Recommendation Systems", "Systems that recommend products or content by customer interest."],
    ["AI за customer service", "Изкуствен интелект, подпомагащ или автоматизиращ обслужването на клиенти.", "AI for Customer Service", "AI supporting or automating your customer support."],
    ["Автоматизация на работни процеси", "Свързване на инструменти, за да текат задачите без ръчна намеса.", "Workflow Automation", "Connecting tools so tasks flow without manual work."],
    ["Предиктивен анализ с AI", "Прогнозиране на бъдещо поведение на клиенти с изкуствен интелект.", "AI Predictive Analytics", "Forecasting future customer behavior with AI."],
    ["Компютърно зрение решения", "Разпознаване и анализ на изображения и видео с алгоритми.", "Computer Vision Solutions", "Recognizing and analyzing images and video with algorithms."],
    ["LLM интеграция за бизнес", "Вграждане на езикови AI модели в продукти и процеси.", "LLM Integration for Business", "Embedding language AI models into products and processes."],
    ["AI агенти разработка", "Автономни AI помощници, изпълняващи конкретни бизнес задачи.", "AI Agent Development", "Autonomous AI assistants performing specific business tasks."],
  ]},
  { id: "crm", icon: "users", name: { bg: "CRM и продажби", en: "CRM & Sales" }, items: [
    ["CRM настройка (HubSpot, Salesforce)", "Внедряване на система за управление на клиенти и продажби.", "CRM Setup (HubSpot, Salesforce)", "Implementing a system for managing customers and sales."],
    ["Sales funnel изграждане", "Изграждане на ясен път от интерес до сключена сделка.", "Sales Funnel Building", "Building a clear path from interest to closed deal."],
    ["Lead nurturing системи", "Автоматизирани поредици, поддържащи интереса на потенциални клиенти.", "Lead Nurturing Systems", "Automated sequences that keep potential customers engaged."],
    ["Email автоматизация", "Автоматични имейли, задействани от действията на клиента.", "Email Automation", "Automatic emails triggered by customer actions."],
    ["Pipeline management", "Организация и проследяване на сделките през различните им етапи.", "Pipeline Management", "Organizing and tracking deals through their stages."],
    ["Customer support софтуер настройка", "Внедряване на система за организирано обслужване на клиенти.", "Customer Support Software Setup", "Implementing a system for organized customer support."],
    ["Help desk системи", "Система за приемане и проследяване на клиентски запитвания.", "Help Desk Systems", "A system for receiving and tracking customer requests."],
    ["Sales enablement консултации", "Съвети и инструменти, помагащи на екипа по продажби да затваря повече сделки.", "Sales Enablement Consulting", "Advice and tools helping your sales team close more deals."],
    ["CRM миграция между платформи", "Прехвърляне на клиентски данни от една CRM система в друга.", "CRM Migration Between Platforms", "Moving customer data from one CRM system to another."],
    ["Loyalty програма разработка", "Система за награждаване на лоялни клиенти с бонуси и отстъпки.", "Loyalty Program Development", "A system rewarding loyal customers with perks and discounts."],
  ]},
  { id: "pr", icon: "radio", name: { bg: "PR и комуникации", en: "PR & Communications" }, items: [
    ["Онлайн PR стратегия", "План за изграждане на публичния образ на бранда онлайн.", "Online PR Strategy", "A plan for building your brand's public image online."],
    ["Криза комуникации", "Подготовка и реакция при ситуация, застрашаваща репутацията на бранда.", "Crisis Communications", "Preparation and response for a reputation-threatening situation."],
    ["Медия outreach", "Свързване с журналисти и медии за отразяване на бизнеса ви.", "Media Outreach", "Connecting with journalists and media to cover your business."],
    ["Press kit изработка", "Готов комплект материали за медии за представяне на бизнеса.", "Press Kit Creation", "A ready media kit for presenting your business."],
    ["Онлайн репутация мениджмънт", "Наблюдение и управление на това как изглежда брандът ви онлайн.", "Online Reputation Management", "Monitoring and managing how your brand appears online."],
    ["Review мениджмънт (Google, Trustpilot)", "Управление на отзивите на клиенти в основните платформи.", "Review Management (Google, Trustpilot)", "Managing customer reviews across major platforms."],
    ["Влогър/инфлуенсър партньорства", "Договаряне на партньорства с влогъри за представяне на бранда.", "Vlogger/Influencer Partnerships", "Arranging partnerships with vloggers to represent your brand."],
    ["Подкаст PR пласиране", "Уговаряне на участия в подкасти за повишаване на видимостта.", "Podcast PR Placement", "Arranging podcast appearances to boost visibility."],
    ["Награди и номинации консултации", "Помощ при кандидатстване за бизнес награди и отличия.", "Awards & Nominations Consulting", "Help applying for business awards and recognitions."],
    ["Investor relations комуникации", "Комуникация с инвеститори относно представянето на бизнеса.", "Investor Relations Communications", "Communication with investors about business performance."],
  ]},
  { id: "translation", icon: "languages", name: { bg: "Преводи и локализация", en: "Translation & Localization" }, items: [
    ["Уебсайт превод", "Превод на сайта на нужните ви езици.", "Website Translation", "Translating your site into the languages you need."],
    ["Съдържание локализация", "Адаптиране на съдържанието културно, не само езиково, за нов пазар.", "Content Localization", "Adapting content culturally, not just linguistically, for a new market."],
    ["Multilingual SEO", "SEO стратегия, съобразена с всеки език и пазар поотделно.", "Multilingual SEO", "SEO strategy tailored to each language and market separately."],
    ["Субтитри за видео", "Превод и синхронизиране на субтитри към видео материал.", "Video Subtitles", "Translating and syncing subtitles for video content."],
    ["Документен превод", "Превод на бизнес документи с внимание към терминологията.", "Document Translation", "Business document translation with attention to terminology."],
    ["App локализация", "Превод и адаптиране на мобилно приложение за нов пазар.", "App Localization", "Translating and adapting a mobile app for a new market."],
    ["Легализиран/заклет превод", "Официален превод на документи с правна тежест.", "Certified/Sworn Translation", "Official translation of documents with legal weight."],
    ["Гласово дублиране", "Озвучаване на видео или реклама на нов език.", "Voice Dubbing", "Voicing video or ads in a new language."],
  ]},
  { id: "training", icon: "graduation-cap", name: { bg: "Обучение и консултации", en: "Training & Consulting" }, items: [
    ["Дигитален маркетинг обучения", "Практическо обучение по дигитален маркетинг за екипа ви.", "Digital Marketing Training", "Hands-on digital marketing training for your team."],
    ["SEO обучения", "Обучение как да поддържате и подобрявате класирането на сайта сами.", "SEO Training", "Training to maintain and improve your site's ranking yourself."],
    ["Social media обучения", "Обучение за самостоятелно управление на социалните мрежи на бранда.", "Social Media Training", "Training to manage your brand's social media independently."],
    ["IT консултации", "Насоки за технологичните решения, подходящи за развитието на бизнеса.", "IT Consulting", "Guidance on the tech choices right for your business growth."],
    ["Уебинари за клиенти", "Онлайн семинари, обучаващи клиентите ви за продукта или темата.", "Client Webinars", "Online seminars educating your customers on a product or topic."],
    ["One-on-one коучинг", "Индивидуални сесии, съобразени точно с вашите въпроси и цели.", "One-on-one Coaching", "Individual sessions tailored exactly to your questions and goals."],
    ["Корпоративни IT обучения", "Обучение на екипа за работа с нови системи и инструменти.", "Corporate IT Training", "Training your team to work with new systems and tools."],
    ["Онлайн курс изработка", "Изграждане на платен онлайн курс от нулата за вашата аудитория.", "Online Course Creation", "Building a paid online course from scratch for your audience."],
  ]},
  { id: "maintenance", icon: "wrench", name: { bg: "Абонаментни и поддръжка услуги", en: "Subscription & Maintenance" }, items: [
    ["Месечна поддръжка на сайт", "Редовни технически грижи, за да работи сайтът ви безпроблемно.", "Monthly Website Maintenance", "Ongoing technical care so your site runs without issues."],
    ["Website-as-a-Service (WaaS)", "Сайт на абонамент — всичко включено срещу фиксирана месечна цена.", "Website-as-a-Service (WaaS)", "A subscription site — everything included for one fixed monthly fee."],
    ["Managed hosting", "Хостинг, за който ние се грижим вместо вас.", "Managed Hosting", "Hosting that we take care of for you."],
    ["Content-as-a-Service", "Редовно ново съдържание за сайта или социалните мрежи на абонамент.", "Content-as-a-Service", "Fresh site or social content on a regular subscription."],
    ["SEO-as-a-Service", "Непрекъсната SEO грижа на месечен абонамент.", "SEO-as-a-Service", "Ongoing SEO care on a monthly subscription."],
    ["Social media-as-a-Service", "Управление на социалните мрежи на месечен абонамент.", "Social Media-as-a-Service", "Social media management on a monthly subscription."],
    ["Технически ъпгрейд пакети", "Еднократно надграждане на остарели части от сайта или системата.", "Technical Upgrade Packages", "A one-time upgrade of outdated parts of a site or system."],
    ["24/7 monitoring услуга", "Постоянно наблюдение на сайта за проблеми и downtime.", "24/7 Monitoring Service", "Constant monitoring of your site for issues and downtime."],
  ]},
  { id: "legal", icon: "scale", name: { bg: "GDPR и правни услуги", en: "GDPR & Legal" }, items: [
    ["GDPR политика и бисквитки", "Задължителните документи за поверителност и съгласие за бисквитки.", "GDPR Policy & Cookies", "The required privacy policy and cookie consent documents."],
    ["Общи условия изработка", "Ясни правила за ползване на сайта или услугата ви.", "Terms of Service Drafting", "Clear rules for using your site or service."],
    ["Политика за поверителност", "Документ, обясняващ как се обработват личните данни на посетителите.", "Privacy Policy", "A document explaining how visitors' personal data is handled."],
    ["Data processing agreement (DPA)", "Договор, уреждащ обработката на лични данни между страни.", "Data Processing Agreement (DPA)", "An agreement governing personal data processing between parties."],
    ["Договори за услуги", "Изготвяне на договори между вас и вашите клиенти.", "Service Agreements", "Drafting contracts between you and your clients."],
    ["Trademark/марка регистрация консултация", "Насоки за регистрация и защита на търговската ви марка.", "Trademark Registration Consulting", "Guidance on registering and protecting your trademark."],
    ["Импресум/декларация за собственик", "Задължителна информация за собственика на сайта според закона.", "Imprint/Owner Disclosure", "Legally required owner information for the site."],
    ["Cookie consent management", "Система за управление на съгласието за бисквитки на сайта.", "Cookie Consent Management", "A system for managing cookie consent on your site."],
    ["GDPR одит", "Проверка доколко бизнесът ви съответства на изискванията на GDPR.", "GDPR Audit", "Checking how well your business complies with GDPR."],
    ["Права на интелектуална собственост консултация", "Съвети за защита на авторски права и интелектуална собственост.", "Intellectual Property Consulting", "Advice on protecting copyright and intellectual property."],
    ["Условия за връщане/рекламации", "Ясни правила за връщане на стоки и решаване на рекламации.", "Returns/Complaints Terms", "Clear rules for returns and handling complaints."],
  ]},
];

// Flatten into a single services array
const SERVICES = [];
CATS.forEach((c) => {
  c.items.forEach((it, i) => {
    SERVICES.push({
      id: `${c.id}-${i}`, cat: c.id,
      name: { bg: it[0], en: it[2] },
      desc: { bg: it[1], en: it[3] },
    });
  });
});
function catOf(id) { return CATS.find((c) => c.id === id); }
const TOTAL_SERVICES = SERVICES.length;
